# Generated by Django 3.2.7 on 2021-10-12 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20211011_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('[0-9]{10,14}$')]),
        ),
    ]
