# Generated by Django 3.2.7 on 2021-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20211012_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='budget',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship',
            field=models.FloatField(null=True),
        ),
    ]
