# Generated by Django 3.2.7 on 2021-10-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20211012_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.BooleanField(null=True),
        ),
    ]
