# Generated by Django 3.2.7 on 2021-10-23 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatars'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 10, 23), null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(to='students.Course'),
        ),
    ]
