# Generated by Django 3.2.7 on 2021-10-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20211024_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='invited',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120)),
                ('invite_code', models.CharField(max_length=120)),
                ('accept', models.BooleanField(null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
