# Generated by Django 3.2.7 on 2021-10-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20211024_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
