# Generated by Django 3.2.7 on 2021-10-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='handler',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
